eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /apia/**
      serviceId: feign-consumer
    api-b:
      path: /apib/**
      serviceId: ribbon-consumer