server:
    port: 8763
spring:
    application:
        name: ribbon-consumer
eureka:
    client:
        serviceUrl:
            defaultZone: http://euraka-server2:8751/eureka/,http://euraka-server1:8761/eureka/