#spring:
#    profiles: euraka-server2
server:
    port: 8751
eureka:
    instance:
        hostname: euraka-server2
        #ip-address: 127.0.0.1
        #prefer-ip-address: true
    client:
        registerWithEureka: false
        #fetchRegistry: false
        serviceUrl:
           defaultZone: http://euraka-server1:8761/eureka/

